apiVersion: v1
kind: Pod
metadata:
  name: debug-pubsub
  namespace: satori
spec:
  containers:
  - name: pubsub
    image: us-west3-docker.pkg.dev/jovial-parsec-428705-r8/satori/pubsub:v2
    command: ["/bin/sh"]
    args: ["-c", "while true; do sleep 30; done;"]
    volumeMounts:
    - name: repos-pubsub
      mountPath: /Satori
  volumes:
  - name: repos-pubsub
    persistentVolumeClaim:
      claimName: repos-pubsub-pvc
