apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: repos-pubsub-sc
provisioner: kubernetes.io/gce-pd
allowVolumeExpansion: true
parameters:
  type: pd-standard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: repos-pubsub-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: repos-pubsub-sc
