apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: repos-synergy-sc
provisioner: kubernetes.io/gce-pd
allowVolumeExpansion: true  # This line enables PVC expansion
parameters:
  type: pd-standard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: repos-synergy-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: repos-synergy-sc
