apiVersion: apps/v1
kind: Deployment
metadata:
  name: synergy
  namespace: satori
spec:
  replicas: 2
  selector:
    matchLabels:
      app: synergy
  template:
    metadata:
      labels:
        app: synergy
    spec:
      containers:
      - name: synergy
        image: us-west3-docker.pkg.dev/jovial-parsec-428705-r8/satori/synergy:v1
        ports:
        - containerPort: 24602
        volumeMounts:
        - name: repos-synergy
          mountPath: /mnt/persistent
        - name: tmp-synergy
          mountPath: /tmp
      volumes:
      - name: repos-synergy
        persistentVolumeClaim:
          claimName: repos-synergy-pvc
      - name: tmp-synergy
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: synergy-service
  namespace: satori
spec:
  selector:
    app: synergy
  ports:
    - protocol: TCP
      port: 24602
      targetPort: 24602
  type: ClusterIP
