apiVersion: v1
kind: Pod
metadata:
  name: psql-test
  labels:
    app: psql-test
spec:
  containers:
  - name: psql
    image: postgres:latest
    command: ["sleep"]
    args: ["3600"]
    volumeMounts:
    - name: ca-cert
      mountPath: /etc/ssl/certs
      readOnly: true
    env:
    - name: PGPASSWORD
      value: "LRKW3lnFqyiR9a4pIIp2ohQiPTzuBEuiPpUrn6GtKfwD2N52Hj3rOrqXZrZ9gPas"
  volumes:
  - name: ca-cert
    secret:
      secretName: satorinet-ca
  restartPolicy: Never
